### ISSUE TITLE
TODO and notes from old repo

### ISSUE THREAD

**Issue by AlenkaF** [arrow-maintenance/arrowdash#17]
Moving list of things to do from https://github.com/thisisnic/arrowdash, see:

- https://github.com/thisisnic/arrowdash/issues/13
- https://github.com/thisisnic/arrowdash/issues/18

Look and feel:
- [x] make the colour look like Arrow _**(Alenka)**_ https://github.com/os-maintenance/arrowdash/pull/18
- [x] put the "last updated" text somewhere better _**(Nic - in progress)**_
- [x] add colours for infoboxes to make look nice and/or consistent
- [x] arrange datatables better so things fit well on screen _**(Nic - in progress)**_

Functionality:
- [x] make dates be nice human-readable ones _**(Nic - in progress)**_
- [x] make it so that when we download list of issues we have both the link and the title **_(Alenka)_** https://github.com/thisisnic/arrowdash/pull/22
- [x] add Stack Overflow and mailing list questions **_(Alenka)_** https://github.com/os-maintenance/arrowdash/pull/6

Code:
- [x]  using templating so we can expand to other languages _**(Nic - in progress)**_
- [x]  add details of virtual environment to README _**(Alenka)**_ https://github.com/thisisnic/arrowdash/pull/16

How to combine the tables?
- [x] yes, let's combine -can we colour the cells to highlight new contributors? 
(https://colorado.posit.co/rsc/nz-quakes/quakes.html - colouring is possible! 
   https://github.com/thisisnic/arrowdash/pull/21
- [x] limit the total number displayed and paginate it
- [x] add tabs for stack overflow - Alenka to connect the Stack Overflow https://github.com/os-maintenance/arrowdash/pull/6
- [x] have the plots on a new tab - could the first one? **(Nic)** https://github.com/os-maintenance/arrowdash/pull/15

Other dash ideas
- [x] maybe the font
- [x] plotly plots? Alenka to look into. Idea: https://grrrck.quarto.pub/mynorfolk-dash/
	- plots from here look cool
	- could we combine PRs and issues for the new contributor stuff?
	- or new contributors vs everyone else
	- put R/PyArrow in top right corner
	https://github.com/thisisnic/arrowdash/pull/23
- [x] 	think about what data we want to plot
- [x] box titles, e.g. (https://jjallaire.github.io/customer-churn-dashboard/)
- [x] pick some nice colours but not too many
- [x] Plot and the bar colour should match

Goal: for now get something good for us and then update later.
